export const alcoholicBeverages = [
  { name: "bourbon", color: "#b04a00" },
  { name: "gin", color: "#dae1e2" },
  { name: "Southern Comfort", color: "#f1c27d" },
  { name: "rye whiskey", color: "#c69c6d" },
  { name: "amaretto", color: "#c49a6c" },
  { name: "vodka", color: "#e6f0f3" },
  { name: "rum", color: "#cd853f" },
  { name: "Irish Whiskey", color: "#bf9b30" },
  { name: "scotch", color: "#ba8b02" },
  { name: "cognac", color: "#993300" },
  { name: "tequila", color: "#f3f3c0" },
  { name: "calvados", color: "#ab6b51" },
  { name: "citrus rum", color: "#ffd700" },
  { name: "apple vodka", color: "#b2ec5d" },
  { name: "applejack", color: "#e1a95f" },
  { name: "citrus vodka", color: "#fde910" },
  { name: "Van Gogh Wild Appel Vodka", color: "#e4c2d5" },
  { name: "spiced rum", color: "#ae0e36" },
  { name: "raspberry vodka", color: "#e30b5d" },
  { name: "galliano", color: "#ffc40c" },
  { name: "white crème de cacao", color: "#ffffff" },
  { name: "peach vodka", color: "#ffcb99" },
  { name: "Irish whiskey", color: "#c9a070" },
  { name: "Jack Daniel's", color: "#a05c17" },
  { name: "OP vodka", color: "#d0efff" },
  { name: "currant vodka", color: "#640125" },
  { name: "light rum", color: "#f0e68c" },
  { name: "Pimm's No. 1", color: "#a76a6a" },
  { name: "crème de noyau", color: "#ffadad" },
  { name: "Seagram's Seven-Crown whiskey", color: "#f7e4d3" },
  { name: "sloe gin", color: "#db5a6b" },
  { name: "orange vodka", color: "#ffa500" },
];

export const nonAlcoholicBeverages = [
  { name: "lime juice", color: "#00ff00" },
  { name: "orange juice", color: "#ffa500" },
  { name: "cranberry juice", color: "#db143c" },
  { name: "grapefruit juice", color: "#fdbcb4" },
  { name: "Juice", color: "#ff7f00" },
  { name: "lemon juice", color: "#fff700" },
  { name: "pineapple juice", color: "#f1c27d" },
];

export const otherBeverages = [
  { name: "egg white", color: "#ffffff" },
  { name: "tonic water", color: "#d0f0c0" },
  { name: "ginger ale", color: "#f0e68c" },
  { name: "lemon-lime soda", color: "#e0ff1e" },
  { name: "maraschino", color: "#ff6347" },
  { name: "cola", color: "#3e1a00" },
  { name: "olive brine", color: "#808000" },
  { name: "orange bitters", color: "#ff4500" },
  { name: "ginger beer", color: "#d2b48c" },
  { name: "7UP", color: "#d0f0c0" },
  { name: "bottled water", color: "#d4f1f9" },
  { name: "Angostura", color: "#8b0000" },
  { name: "champagne", color: "#fddc6c" },
  { name: "Peychaud's", color: "#e37795" },
  { name: "sweet iced tea", color: "#c2a078" },
  { name: "cream", color: "#fffdd0" },
  { name: "Coca-cola", color: "#3e1a00" },
  { name: "simple syrup", color: "#f5f5dc" },
  { name: "grenadine", color: "#e0115f" },
  { name: "club soda", color: "#d4f1f9" },
];
