export const alcoholicBeverages = [
  "bourbon",
  "gin",
  "Southern Comfort",
  "rye whiskey",
  "amaretto",
  "vodka",
  "rum",
  "Irish Whiskey",
  "scotch",
  "cognac",
  "tequila",
  "calvados",
  "citrus rum",
  "apple vodka",
  "applejack",
  "citrus vodka",
  "Van Gogh Wild Appel Vodka",
  "spiced rum",
  "raspberry vodka",
  "galliano",
  "white crème de cacao",
  "peach vodka",
  "Irish whiskey",
  "Jack Daniel's",
  "OP vodka",
  "currant vodka",
  "light rum",
  "Pimm's No. 1",
  "crème de noyau",
  "Seagram's Seven-Crown whiskey",
  "sloe gin",
  "orange vodka",
];

export const nonAlcoholicBeverages = [
  "lime juice",
  "orange juice",
  "cranberry juice",
  "grapefruit juice",
  "Juice",
  "lemon juice",
  "pineapple juice",
];

export const otherBeverages = [
  "egg white",
  "tonic water",
  "ginger ale",
  "lemon-lime soda",
  "maraschino",
  "cola",
  "olive brine",
  "orange bitters",
  "ginger beer",
  "7UP",
  "bottled water",
  "Angostura",
  "champagne",
  "Peychaud's",
  "sweet iced tea",
  "cream",
  "Coca-cola",
  "simple syrup",
  "grenadine",
  "club soda",
];
